config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :posts

root 'creatives#index'

get '/creatives/:id', to: 'creatives#show', as: 'creatives'


end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	validates :title, presence: true, length: {minimum: 5}
	validates :body, presence: true

	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/creatives_controller.rb
class CreativesController < ApplicationController
  layout "creative"

  	def index
		@posts = Post.all.order('created_at desc')
	end

	def show
		@post  = Post.find(params[:id])
		@posts = Post.order('created_at desc').limit(4).offset(0)
	end

private

	def post_params
		params.require(:post).permit(:title, :body)
	end
	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
		@posts = Post.all.order('created_at desc')
	end

	def show
		@posts = Post.find(params[:id])
		@posts = Post.order('created_at desc').limit(4).offset(1)
	end

private

	def post_params
		params.require(:post).permit(:title, :body)
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/creatives/_bg_primary.html.erb
<section class="bg-primary" id="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <h2 class="section-heading">Who is Jose Vega?</h2>
                <hr class="light">
                <p class="text-faded">A Full Stack Developer from Honduras. I believe in delivering more than just a product, I believe in creating experiences. </p>
                <p class="text-faded">A problem solver and strategist at your service. </p>
                <a href="#services"" class="btn btn-default btn-xl page-scroll">Get Started</a>
            </div>
        </div> 
    </div>
</section>

app/views/creatives/_call_to_action.html.erb
<aside class="bg-dark">
    <div class="container text-center">
        <div class="call-to-action">
            <h3>Have a project in mind that you want to get started?</h3>
            <br>
            <br>
            <a href="#contact" class="btn btn-default btn-xl wow tada">Contact Me!</a>
        </div>
    </div>
</aside>

app/views/creatives/_contact.html.erb
  <section id="contact">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <h2 class="section-heading">Let's Get In Touch!</h2>
                <hr class="primary">
                <p>Give me a call or send me an email please include your name and contact information.</p>
            </div>
            <div class="col-lg-4 col-lg-offset-2 text-center">
                <i class="fa fa-phone fa-3x wow bounceIn"></i>
                <p>####-####</p>
            </div>
            <div class="col-lg-4 text-center">
                <i class="fa fa-envelope-o fa-3x wow bounceIn" data-wow-delay=".1s"></i>
                <p><a href="mailto:jose@hekahnd.com">jose@hekahnd.com</a></p>
            </div>
        </div>
    </div>
</section>

app/views/creatives/_header.html.erb
<header id= "page-top">
    <div class="header-content">
        <div class="header-content-inner">
            <h1>JOSE VEGA</h1>
            <hr>
            <p>A showcase of the few proyects I have created</p>
            <a href="#about" class="btn btn-primary btn-xl page-scroll">About Me</a>
        </div>
    </div>
</header>

app/views/creatives/_navbar.html.erb
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand page-scroll" href="#page-top"><i class="fa fa-code fa-lg" aria-hidden="true"></i> Jose Vega</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="page-scroll" href="#about">About</a>
                </li>
                <li>
                    <a class="page-scroll" href="#services">Services</a>
                </li>
                <li>
                    <a class="page-scroll" href="#portfolio">Portfolio</a>
                </li>
                <li>
                    <a class="page-scroll" href="#contact">Contact</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/creatives/_portfolio.html.erb
<div class="col-lg-12 text-center">
                <h2 class="section-heading">Projects</h2>
                <hr class="primary">
            </div>
<section class="no-padding" id="portfolio">
    <div class="container-fluid">
        <div class="row no-gutter">
            <% @posts.each do |post| %>
            <div class="col-lg-4 col-sm-6">
                <a href="#">
                <%= link_to creatives_path(post), :class => "portfolio-box" do %>
                    <%= image_tag post.image, class: "img-responsive", alt: "" %>
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                </div>
                                <div class="project-name">
                                <%= post.title %>
                            </div>
                        </div>
                    </div>  
                <%end%>    
                </a> 
            </div>
            <%end%>

        </div>
    </div>
</section>

app/views/creatives/_services.html.erb
<section id="services">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">At Your Service</h2>
                <hr class="primary">
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <i class="fa fa-4x fa-user wow rubberBand text-primary"></i>
                    <h3>UX/UI Design</h3>
                    <p class="text-muted">Users should navigate your product with ease.</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <i class="fa fa-4x fa-diamond wow bounceIn text-primary" data-wow-delay=".1s"></i>
                    <h3>Web/App Development</h3>
                    <p class="text-muted">Beautiful, useful apps. Application molded to you and your client's needs.</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <i class="fa fa-4x fa-pencil-square-o wow bounceInUp text-primary" data-wow-delay=".2s"></i>
                    <h3>Logo Design</h3>
                    <p class="text-muted">Smart graphic design.</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <i class="fa fa-4x fa-heart wow lightSpeedIn text-primary" data-wow-delay=".3s"></i>
                    <h3>Brand Identity</h3>
                    <p class="text-muted">Personification by adding value to your business. </p>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/creatives/index.html.erb
<%= render 'navbar' %>
<%= render 'header' %>
<%= render 'bg_primary' %>
<%= render 'services' %>
<%= render 'portfolio' %>
<%= render 'call_to_action' %>
<%= render 'contact' %>

app/views/creatives/show.html.erb
    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top"> 
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
<div class="show_page">        
        <div class="navbar-header"> 
</div>              
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>                
            </button>
 
            <a class="navbar-brand page-scroll" href="/"><i class="fa fa-code fa-lg" aria-hidden="true"></i> back</a>           
        </div>         
        <!-- /.navbar-collapse -->      
    </div>
    <!-- /.container-fluid -->
    </nav>
<br>
    <!-- Page Content -->
    <div class="container">

        <!-- Portfolio Item Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header"><%= @post.title %>
                </h1>
            </div>
        </div>
        <!-- /.row --> 

        <!-- Portfolio Item Row -->
        <div class="row">

            <div class="col-md-8">
                <%= image_tag @post.image, class: 'img-responsive' %>
            </div>

            <div class="col-md-4">
                <h3>Description</h3>
                <p><%= @post.body %></p>
            </div>

        </div>
        <!-- /.row -->

        <!-- Related Projects Row -->
        <div class="row">

            <div class="col-lg-12">
                <h3 class="page-header">More Projects</h3>
            </div>

            <% @posts.each do |post| %>
                <div class="col-sm-3 col-xs-6">
                    <%= link_to creatives_path(post) do %>
                        <%= image_tag post.image, class: 'img-responsive portfolio-item' %>
                    <% end %>    
                </div>  
            <% end %>  

        </div>
        <!-- /.row -->
    </div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JoseVegaPortfolio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>	
    <%= yield %>
  </body>
</html>

app/views/layouts/creative.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jose Vega Portfolio</title>
  <%= stylesheet_link_tag 'creative/manifest.css', media: 'all' %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
   <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet" type='text/css'> 
  <%= javascript_include_tag 'creative/manifest.js' %>
  <%= csrf_meta_tags %>
</head>

<body>

<%= yield %>

</body>
</html>